project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "World Economics"
  author:
    - Jiayi Niu (jn2941)
    - Ruibin Lyu (rl3501)
  repo-url: https://github.com/JiayiNiu2023/5702_Final_Project_Group37
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


